title: Luke
email: acatia@mail.com
baseurl: "/website"
url: "https://acatiadroid.github.io"
github_username:  acatiadroid

show_excerpts: true
permalink: /:collection/:year-:month-:day-:title:output_ext

theme: minima
plugins:
  - jekyll-feed